/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CMLogo: typeof import('./src/components/CMLogo.vue')['default']
    CompanyRegistration: typeof import('./src/components/auth/CompanyRegistration.vue')['default']
    CorporateFareOutlined: typeof import('./src/components/icons/CorporateFareOutlined.vue')['default']
    DarkModeFilled: typeof import('./src/components/icons/DarkModeFilled.vue')['default']
    EmptyLayout: typeof import('./src/components/layout/EmptyLayout.vue')['default']
    FilledDarkModeFilled: typeof import('@components/icons/DarkModeFilled.vue')['default']
    FormatListNumberedFilled: typeof import('./src/components/icons/FormatListNumberedFilled.vue')['default']
    FundRegistration: typeof import('./src/components/auth/FundRegistration.vue')['default']
    GroupsFilled: typeof import('./src/components/icons/GroupsFilled.vue')['default']
    HomeFilled: typeof import('./src/components/icons/HomeFilled.vue')['default']
    LightModeFilled: typeof import('./src/components/icons/LightModeFilled.vue')['default']
    LogOutFilled: typeof import('./src/components/icons/LogOutFilled.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCollapseTransition: typeof import('naive-ui')['NCollapseTransition']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NThemeEditor: typeof import('naive-ui')['NThemeEditor']
    RedeemFilled: typeof import('./src/components/icons/RedeemFilled.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenu: typeof import('./src/components/menu/SideMenu.vue')['default']
    UserRegistration: typeof import('./src/components/auth/UserRegistration.vue')['default']
    VisibilityFilled: typeof import('./src/components/icons/VisibilityFilled.vue')['default']
    VisibilityOffFilled: typeof import('./src/components/icons/VisibilityOffFilled.vue')['default']
    VisibilityOffFilledDarkModeFilled: typeof import('./src/components/icons/VisibilityOffFilledDarkModeFilled.vue')['default']
  }
}
