name: mobile
description: Mobile application for fitness tracking. Created by flint3s fot kokoc hack. 2023

publish_to: 'none'

version: 1.0.1


environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  auto_route: ^7.8.3
  get_it: ^7.6.4
  shared_preferences: ^2.2.1
  flutter_svg: ^2.0.7
  dio: ^5.3.3
  provider: ^6.0.5
  internet_connection_checker: ^1.0.0+1
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  fl_chart: ^0.63.0
  flutter_native_splash: ^2.3.2
  flutter_splash_screen: ^2.0.1+1
  health: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  auto_route_generator: ^7.3.1
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21


flutter_native_splash:
  color: '#ffffff'
  image: 'assets/splashscreen.png'


flutter:
  uses-material-design: true

  assets:
    - assets/onboarding/hello.svg
    - assets/onboarding/sport.svg
    - assets/onboarding/hands.svg
    - assets/splashscreen.png
    - assets/icon.png
