name: Server CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN_SERVER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN_SERVER }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./server/
          push: true
          tags: mindlessdoc/kokoc-hack-server:0.0.3

      - name: Invoke deployment Portainer hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          data: '{ "deploy": "true" }'